[package]
name    = "agent-desktop-windows"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
agent-desktop-core.workspace = true
thiserror.workspace          = true
